version: "3.7"

services:
  corporationapp:
    container_name: corporationapp
    build:
      context: .
      dockerfile: dockerfile
    command: sh /var/www/html/node_start.sh
    volumes:
      - ./:/var/www/html
    ports:
      - 3001:3001

    working_dir: /var/www/html
    networks:
      - mongodb_net
networks:
  mongodb_net:
    external: true
    name: mongodb_net

